const path = require('path');
const archiver = require('archiver');
const generationWorker = require('../workers/generationWorker');

class DownloadController {
  static async downloadExtension(req, res) {
    try {
      const { token } = req.params;
      if (!token) return res.status(400).json({ error: 'Download token is required.' });

      // Try to get the real job files from the worker
      let files = null;
      let extName = 'antigravity-extension';
      try {
        const job = await generationWorker.getJobStatus(token);
        if (job && job.files && job.files.length > 0) {
          files = job.files;
          extName = (job.prompt || 'extension').split(' ').slice(0, 3).join('-').toLowerCase().replace(/[^a-z0-9-]/g, '');
        }
      } catch (_) { /* Job not found — use fallback */ }

      res.setHeader('Content-Disposition', `attachment; filename="${extName}.zip"`);
      res.setHeader('Content-Type', 'application/zip');

      const archive = archiver('zip', { zlib: { level: 9 } });
      archive.on('error', err => { throw err; });
      archive.pipe(res);

      if (files && files.length > 0) {
        // Serve the REAL generated extension files
        for (const file of files) {
          archive.append(file.content, { name: file.path });
        }
      } else {
        // Fallback: minimal valid MV3 extension
        const manifest = {
          manifest_version: 3,
          name: 'Extensio.ai Extension',
          version: '1.0.0',
          description: 'Generated by Extensio.ai AI Engine.',
          action: { default_popup: 'popup.html', default_title: 'Extensio.ai' },
          permissions: ['activeTab', 'scripting'],
          host_permissions: ['<all_urls>']
        };
        archive.append(JSON.stringify(manifest, null, 2), { name: 'manifest.json' });

        const popup = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8">
<style>body{width:280px;padding:20px;font-family:system-ui,sans-serif;background:#0b0b0f;color:#e2e8f0;margin:0;text-align:center;}
h2{color:#a78bfa;font-size:16px;} button{width:100%;padding:10px;background:#6366f1;border:none;color:#fff;border-radius:8px;cursor:pointer;font-weight:600;margin-top:12px;}
p{font-size:12px;color:#64748b;}</style></head><body>
<h2>⚡ Extensio.ai</h2><p>Your extension is ready!</p>
<button onclick="chrome.tabs.query({active:true,currentWindow:true},t=>chrome.scripting.executeScript({target:{tabId:t[0].id},func:()=>alert('Extensio.ai extension active!')}))">
Activate</button></body></html>`;
        archive.append(popup, { name: 'popup.html' });
      }

      await archive.finalize();
    } catch (error) {
      console.error('Download error:', error);
      if (!res.headersSent) res.status(500).json({ error: error.message });
    }
  }
}

module.exports = DownloadController;
